### ISSUE TITLE
certificate verify failed: self signed certificate in certificate chain - error during cvd update 

### ISSUE THREAD

**Issue by lirigithub** [Cisco-Talos/cvdupdate#23] opened 2021-04-20 10:38 UTC
Hi,

During running 'cvd update' on my machine, I get an error of:

"requests.exceptions.SSLError: HTTPSConnectionPool(host='database.clamav.net', port=443): Max retries exceeded with url: /main-59.cdiff (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1076)')))"

Is there a way to disable the certificate check here?
Or do you have any other suggestion for solution. I have tried several of different solutions, but couldn't solve it.

Thanks s lot.

**Comment by micahsnyder** [comment] 2021-04-20 15:21
Hi @lirigithub,

I can't recommend disabling SSL certificate verification.  

It's hard to say for sure what the issue is.  This may help: https://stackoverflow.com/questions/51390968/python-ssl-certificate-verify-error

It may be that your certificate store is missing the Digicert root CA, which signs the Cloudflare cert. Cloudflare is our CDN for database.clamav.net. 

What OS are you on?

**Comment by lirigithub** [comment] 2021-04-22 10:21
Hi @micahsnyder,

We want to download the updates as a mirror in one server from our own clamAv DB mirror that is being updated on a daily basis and publicly available. How can it be done using cvd update?
It seems there that it is hard coded looking on database.clamav.net.

I tried to edit the configuration file of config.json, and then it is downloading from the mirror, however, this way doesn't seems the correct way to me. Is there other way to change it?

Also, when I do change the config.json, it downloads the daily.cvd, but fails to download the main.cvd due to the error: "ailed to download main.cvd header to check the version #." Do you know what can be the root cause of it?

**Comment by micahsnyder** [comment] 2021-04-22 18:49
You should be able to manually change the `"url"` in `config.json` for `main.cvd`, `daily.cvd`, and `bytecode.cvd` to point to your own mirror. You should probably also then change the `"DNS field"` to `0` for each as well so that it tries to download the header for the version # check. 

You could also use `cvd remove` and `cvd add` to replace the databases in your config with new ones that have different URLs. 

But be warned that when HTTP is used for the version check instead of DNS, it will use the HTTP `Range` header to request the first 96 bytes of the file. This means your mirror's HTTP server must support HTTP `Range` requests or it may download the entire database for the version check 😬.  For example, Python's built-in `http.server` (formerly `SimpleHTTPServer` in Python 2.7) doesn't support Range requests, so for testing CVDUpdate, I use the 3rd party `rangehttpserver` Python package.

**Comment by micahsnyder** [comment] 2021-04-22 18:52
I forgot -- the HTTP version check does also try to use the "If-Modified-Since" HTTP header as well, in case the Range request doesn't work, but support may vary for this feature as well and I haven't tested it as thoroughly.

**Comment by micahsnyder** [comment] 2021-05-03 23:22
@lirigithub may I close this issue?

**Comment by lirigithub** [comment] 2021-05-04 10:26
For now yes, Thank you!

**Closed** 2021-05-04 16:51 UTC
