### ISSUE TITLE
When running cvd I get error on unittest module

### ISSUE THREAD

**Issue by lirigithub** [Cisco-Talos/cvdupdate#16] opened 2021-04-08 12:57 UTC
Hi

I try to install the cvdupdate using pip install on my linux (based on centos 7) machine.

I get the following issue:

# ./cvd --help

Traceback (most recent call last):
  File "./cvd", line 6, in <module>
    from cvdupdate.__main__ import cli
  File "<my path>/Python/lib/python3.7/site-packages/cvdupdate/__main__.py", line 38, in <module>
    import coloredlogs
  File "<my path>/Python/lib/python3.7/site-packages/coloredlogs/__init__.py", line 211, in <module>
    from humanfriendly import coerce_boolean
  File "<my path>/Python/lib/python3.7/site-packages/humanfriendly/__init__.py", line 20, in <module>
    from humanfriendly.compat import is_string, monotonic
  File "<my path>/Python/lib/python3.7/site-packages/humanfriendly/compat.py", line 68, in <module>
    import unittest
**ModuleNotFoundError: No module named 'unittest**'

What is the issue here?

**Comment by micahsnyder** [comment] 2021-04-08 16:35
I don't know! `unittest` should come built-in to python.  You could try to run `python3 -m pip install unittest` to see if it can be installed separately.

**Comment by micahsnyder** [comment] 2021-04-15 19:07
@lirigithub are you still having this issue?

**Comment by lirigithub** [comment] 2021-04-22 10:13
Yes. For now, I marked it as a comment in line 68 in /opt/CPsuite-R81.10/fw1/Python/lib/python3.7/site-packages/humanfriendly/compact.py.
There there is a comment that it will be removed. Do you know when it will be done?

**Comment by micahsnyder** [comment] 2021-04-22 18:38
I wouldn't know. `humanfriendly` is a dependency of the `coloredlogs` package that CVDUpdate uses to have colorful logs. 

Based on the path `/opt/CPsuite-R81.10/fw1/Python/lib/python3.7`, I suspect the issue is with the checkpoint firewall python installation missing the `unittest` package (which is super weird). 

By chance can you install python 3.6+ some other way to run CVDUpdate?

**Comment by micahsnyder** [comment] 2021-05-03 23:22
May I close this issue?

**Comment by lirigithub** [comment] 2021-05-04 10:26
For now yes. Thank you!

**Closed** 2021-05-04 16:52 UTC
